/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.algebra;

import hr.algebra.dal.RepositoryFactory;
import hr.algebra.model.MovieArchive;
import hr.algebra.model.User;
import hr.algebra.utils.JAXBUtilis;
import hr.algebra.utils.MessageUtils;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Nikola
 */
public class MainForm extends javax.swing.JFrame {

    private static final String UPLOAD_MOVIES="Upload movies";
    private static final String EDIT_MOVIES="Edit movies";
    private static final String FAVOURITE_MOVIES="Favourite movies";
    private static final String FAVOURITE_GENRES="Favourite genres";
    private static int ADMINISTRATOR=1;
    private static int USER=2;
    private static final String ARHIVEXML = "arhive.xml";
    private final User user;

    /**
     * Creates new form MainForm
     */
     public MainForm(User user) {

        initComponents();
        this.user=user;
        configurePanles();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        tpContent = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuMain = new javax.swing.JMenu();
        miSave = new javax.swing.JMenuItem();
        MiLogout = new javax.swing.JMenuItem();
        MiExit = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuMain.setText("Menu");

        miSave.setText("Save to xml");
        miSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSaveActionPerformed(evt);
            }
        });
        menuMain.add(miSave);

        MiLogout.setText("Log out");
        MiLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiLogoutActionPerformed(evt);
            }
        });
        menuMain.add(MiLogout);

        MiExit.setText("Exit");
        MiExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiExitActionPerformed(evt);
            }
        });
        menuMain.add(MiExit);

        jMenuBar1.add(menuMain);
        menuMain.getAccessibleContext().setAccessibleName("Menu");

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpContent, javax.swing.GroupLayout.DEFAULT_SIZE, 1405, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpContent, javax.swing.GroupLayout.DEFAULT_SIZE, 859, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSaveActionPerformed
        try {
            JAXBUtilis.save(new MovieArchive(RepositoryFactory.getRepository().selectMovies()), ARHIVEXML);
        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        MessageUtils.showInformationMessage("ALL DONE", "Movies saved to arhive.xml");
    }//GEN-LAST:event_miSaveActionPerformed

    private void MiLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiLogoutActionPerformed
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_MiLogoutActionPerformed

    private void MiExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiExitActionPerformed
        dispose();
    }//GEN-LAST:event_MiExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MiExit;
    private javax.swing.JMenuItem MiLogout;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuMain;
    private javax.swing.JMenuItem miSave;
    private javax.swing.JTabbedPane tpContent;
    // End of variables declaration//GEN-END:variables

    private void configurePanles() {
        
        if (user.getUserType() == ADMINISTRATOR) {
            tpContent.add(UPLOAD_MOVIES, new UploadMoviesPanel());
            tpContent.add(EDIT_MOVIES, new EditMoviesPanel());
            tpContent.add(FAVOURITE_GENRES, new FavouriteGenresPanel(user));
        }
        
        if (user.getUserType() == USER) {
           tpContent.add(EDIT_MOVIES, new EditMoviesPanel());
            tpContent.add(FAVOURITE_GENRES, new FavouriteGenresPanel(user));
        }
    }
}
